import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

// Define the API slice
export const apiSlice = createApi({
  reducerPath: 'api',
  baseQuery: fetchBaseQuery({ baseUrl: '/api' }), // Replace `/api` with your base URL
  endpoints: (builder) => ({
    // Example endpoint
    fetchExampleData: builder.query({
      query: () => 'example-endpoint', // Replace with your endpoint
    }),
  }),
});

// Export hooks generated by createApi
export const { useFetchExampleDataQuery } = apiSlice;
