export const collectionsList = [
        {name:"Gold with Lab Daimonds",slug:"gold-with-lab"},
        {name:"Wedding Collection",slug:"wedding"},
        {name:"Luxury Vault",slug:"luxury-vault"},
        {name:"Budget Picks",slug:"budget-picks"},
        {name:"Top Products",slug:"top-products"},
        {name:"Hot Picks",slug:"hot-picks"},
        {name:"Anniversary",slug:"anniversary"},
        {name:"Engagement",slug:"engagement"},
        {name:"Proposal",slug:"proposal"},
        {name:"Festivals",slug:"festivals"},
        {name:"For Mother",slug:"for-mother"},
        {name:"For Sister",slug:"for-sister"},
        {name:"For Wife",slug:"for-wife"},
        {name:"For Husbands",slug:"for-husbands"},
        {name:"For Girlfriend",slug:"for-girlfriend"},
]